### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by fried** [zodb/relstorage#10]
On attempted install the use of 'file' in setup.py:41 causes the install to bomb out. It should be 'open' right?

Beyond this how compatible is RelStorage with python3

**Comment by ztane** [comment]
And I've actually been using it for a (very limited) application successfully in production.

**Comment by mhucka** [comment]
I discovered this discussion while looking for a Python 3 compatible version of RelStorage.  Could someone tell me what is the status of Python 3 support? The work by @ztane looks promising. Is it considered stable and safe to use?

**Comment by ztane** [comment]
I don't know about that, since you're absolutely the first person to comment on this. I am using it currently in my app, but my application is using a very limited feature set - but there this certainly "works for me™".

**Comment by mhucka** [comment]
Thanks for your reply!

**Comment by jamadden** [comment]
Moved to #55.
