### ISSUE TITLE
zodbconvert skips blobs silently

### ISSUE THREAD

**Issue by jensens** [zodb/relstorage#12]
using as source a filesystem+blobstorage where blobstorage is not allowed access due to missing permissions, blobs are silently ignored. I'd expect here at least a warning.

**Comment by jamadden** [comment]
If I understand correctly (the source is a FileStorage, and the user running zodbconvert doesn't have operating system permissions to access the `blob-dir`, so existing blob data is silently skipped), then that's an issue to raise on the zopefoundation/ZODB tracker: zodbconvert is essentially storage agnostic, it doesn't really know anything special about other storages or how they are laid out or what warnings they should/shouldn't raise.

**Comment by jamadden** [comment]
AFAICS, the FileStorage code should raise an error on initialization if the `blob-dir` exists but isn't accessible. Please feel free to open a ZODB issue and link it back here if that's not the case. Please feel free to re-open if I misunderstand the problem.

It *may* be possible to neglect to specify the `blob-dir` in the zodbconvert configuration and that can lead to a similar issue in some cases (see #24).
