### ISSUE TITLE
RelStorage = 2.0.0b5 Missing adapters

### ISSUE THREAD

**Issue by papachoco** [zodb/relstorage#121]
It seems the egg in PyPI for RelStorage = 2.0.0b5 does not have the adapters.* packages. I.E. the source (RelStorage-2.0.0b5.tar.gz) does contain the path relstorage.adapters.mysql, but when I do easy-install  RelStorage==2.0.0b5 the egg has those folders missing

Carlos

**Comment by jamadden** [comment]
Thank you for the report. This is due to a manual listing of `packages` in `setup.py` instead of using `find_packages`. It doesn't manifest itself in an editable installation (which sadly is all that gets tested, so it took awhile to track this down.)

**Comment by jamadden** [comment]
2.0b6 is now available to correct this.
