### ISSUE TITLE
Have you considered using stored procedures (or prepared statements) for Postgres?

### ISSUE THREAD

**Issue by jimfulton** [zodb/relstorage#148]
It looks like you could make a lot fewer server calls with some PL/pgSQL functions.

Very few statements are prepared (automatic with pl/pgSQL functions). Have you looked possible performance benefits of compiling most statements on every use?

**Comment by jamadden** [comment]
We do use a prepared statement for PostgreSQL for one very common operation, polling for the latest transaction id (https://github.com/zodb/relstorage/blob/master/relstorage/adapters/postgresql/connmanager.py#L90). But doing so requires (special support from the poller)[https://github.com/zodb/relstorage/blob/master/relstorage/adapters/postgresql/adapter.py#L94) object.

We also use stored procedures [in oracle](https://github.com/zodb/relstorage/blob/master/relstorage/adapters/oracle/mover.py#L131) where possible.

In general, stored procedures and prepared statements have different limitations and calling conventions across all three supported databases, so plumbing them into every query that's not already using them (e.g., all the generic queries in relstorage/adapters/*py) would require quite a bit more factorization than is present, complicating the code quite a bit (I suspect). For example, in MySQL, you have to explicitly execute 'SET' statements for each parameter in a prepared statement  (AFAICS), whereas in PostgreSQL you can inline them right into the call. I'm guessing the places we already use stored procs/prepared statements were considered low-hanging fruit with the biggest bang for the buck when they were implemented.

Sometimes drivers will automatically prepare statements. I know that was common with Java drivers, I don't know if any drivers we use here do that.

One common issue people encounter with using prepared statements or stored procedures, depending on the database, is that the plan tends to get reused. When the database is capable of using histogram stats, for example, based on the exact parameter values, the generic plan may be much less optimal than the specific plan. I know this used to be a big problem for us in Oracle. Postgres supposedly only reverts to a generic plan these days if it thinks that won't happen; I don't know how well that works. I don't know how MySQL deals with the issue at all.

**Comment by jimfulton** [comment]
On Thu, Dec 15, 2016 at 9:55 AM, Jason Madden <notifications@github.com>
wrote:

> We do use a prepared statement for PostgreSQL for one very common
> operation, polling for the latest transaction id (https://github.com/zodb/
> relstorage/blob/master/relstorage/adapters/postgresql/connmanager.py#L90).
> But doing so requires (special support from the poller)[
> https://github.com/zodb/relstorage/blob/master/relstorage/adapters/
> postgresql/adapter.py#L94) object.
>
> We also use stored procedures in oracle
> <https://github.com/zodb/relstorage/blob/master/relstorage/adapters/oracle/mover.py#L131>
> where possible.
>
> In general, stored procedures and prepared statements have different
> limitations and calling conventions across all three supported databases,
> so plumbing them into every query that's not already using them (e.g., all
> the generic queries in relstorage/adapters/*py) would require quite a bit
> more factorization than is present, complicating the code quite a bit (I
> suspect).
>
Or simplify it, depending on how APIs are factored. <shrug>


> For example, in MySQL, you have to explicitly execute 'SET' statements for
> each parameter in a prepared statement (AFAICS), whereas in PostgreSQL you
> can inline them right into the call. I'm guessing the places we already use
> stored procs/prepared statements were considered low-hanging fruit with the
> biggest bang for the buck when they were implemented.
>
> Sometimes drivers will automatically prepare statements. I know that was
> common with Java drivers, I don't know if any drivers we use here do that.
>
That's an interesting point.  I think at one point, the dbapi threatened to
do that sort of thing.

> One common issue people encounter with using prepared statements or stored
> procedures, depending on the database, is that the plan tends to get
> reused. When the database is capable of using histogram stats, for example,
> based on the exact parameter values, the generic plan may be much less
> optimal than the specific plan. I know this used to be a big problem for us
> in Oracle. Postgres supposedly only reverts to a generic plan these days if
> it thinks that won't happen; I don't know how well that works. I don't know
> how MySQL deals with the issue at all.
>
I was initially just wondering of there was an attempt to measure this.
I'll do some experiments with Postgres and report back here. (No promises
of when, likely not till next year.)

Jim

-- 
Jim Fulton
http://jimfulton.info

**Comment by jamadden** [comment]
> I was initially just wondering of there was an attempt to measure this.
I'll do some experiments with Postgres and report back here. (No promises
of when, likely not till next year.)

I haven't done any such measurements, but I agree they would be good to have! (The generic vs explicit plan issue can make them difficult to accurately get, though, since it will depend on the state of the statistics.)

**Comment by jimfulton** [comment]
I finally got around to trying this.  I added a prepared statement for load_current.

Results here: https://gist.github.com/jimfulton/b6d416635ea7a2f21f2aa33d44535e05

Cold reads with a prepared statement are ~30% faster.

Like finding money in the couch. :)

I'll create a PR to use prepared statements in the Postgres adapter.

I'll also play with some of the other queries to see if there's more free $ to be found.

**Comment by jamadden** [comment]
As part of the work in #156 I'm doing some refactoring work ('prep-statements' branch) to make it easier to deal with prepared statements (the one place that postgres was already using them was hacked in). I'll go ahead and add the postgres prepared statement when I PR that branch.

**Comment by jimfulton** [comment]
Cool.

BTW, in looking at Newt write performance, I looked at preparing the upsert statements (delete+insert) used to write the data and it had no measurable impact on performance.  I suspect it's a win for loads because the execution time is so small compared to the (also small but non-zero) prepare time.

**Comment by jamadden** [comment]
Closed by #157.
