### ISSUE TITLE
Checking keep.history all over the place and going through extra hoops seems painful

### ISSUE THREAD

**Issue by jimfulton** [zodb/relstorage#149]
I wonder if it wouldn't be simpler to have separate storages and to not go through as much transactuion management machinery for history-free storages.  For example, relstorage caries transaction meta data and goes through the motion of saving it when nothing will be done with it.

**Comment by jamadden** [comment]
I agree that there are a lot of `if` checks around `keep_history` and I'd generally like to see those go away, to the extent that it doesn't complicate and obfuscate the code. History-free databases were a relatively late addition to RelStorage (dating to version 1.4 in 2009) and the ifs were probably the simplest way to add it while still sharing the maximum amount of code.

Some of them can probably be replaced with statement lookups (e.g., a HISTORY_FREE_STATEMENTS and a HISTORY_PRESERVING_STATEMENTS dictionary that get chosen to be instance variables at construction time), but that unfortunately loses the readability of the inline statement. Likewise with subclassing and attributes. So it's not clear to me what the best, most readable option would be.

As far as transaction meta data goes, in history-free databases that never actually goes anywhere, the methods are no-ops. An extra Python method call doesn't seem like much of a price to pay.

**Comment by jimfulton** [comment]
Just noting as I was reading code. In the long run, I still think it would likely be cleaner to separate this into separate classes.
