### ISSUE TITLE
CI: Update to 3.6.0 final

### ISSUE THREAD

**Issue by jamadden** [zodb/relstorage#151]
- [ ] Now that 3.6.0 final is out, update Travis CI to use it instead of an RC.
- [ ] Also we should enable 3.6 for appveyor, whenever they get around to adding it. (We can also install it ourself, I think.)
- [x] The manylinux image should have 3.6 [included soon](https://github.com/pypa/manylinux/issues/82) and when it does we should build a 2.0 wheel.

**Comment by njsmith** [comment]
manylinux docker images now have 3.6
