### ISSUE TITLE
asynchronous time-machine

### ISSUE THREAD

**Issue by jimfulton** [zodb/relstorage#171]
Time-travel is a nice feature. For some applications it's critical. I've been told by a major ZODB user that they never pack. But history-free storage is sooooo much faster.  Maybe there are opportunities to make it go even faster (#170).

I wonder if it would make sense to provide an option to publish transaction data to asynchronous channels like Kinesis or Kafka so that time machines could be build asynchronously.  Maybe even storing data in some cheap offline storage like S3 or Glacier for auditing.

**Comment by jamadden** [comment]
I can imagine value in that, but it also seems beyond the scope of RelStorage proper. Couldn't that be accomplished with a storage wrapper?

**Comment by jimfulton** [comment]
Ah, good point. And good idea!

BTW, this came up recently in a discussion with a potential client who needed (more than) the speed of history-free but also needed a time machine. So the need isn't hypothetical. :)
