### ISSUE TITLE
needs libffi-dev

### ISSUE THREAD

**Issue by thet** [zodb/relstorage#187]
installing RelStorage 2.0 complains about:

```
Getting distribution for 'RelStorage==2.0.0'.
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
 #include <ffi.h>
                 ^
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1
```

On Debian/Ubuntu one needs to install ``libffi-dev``.

That should maybe be mentioned in the docs.

**Comment by jamadden** [comment]
Is there a reason the provided binary wheels aren't being used?

`libffi-dev` is a dependency of cffi, and the cffi docs [do mention this](https://cffi.readthedocs.io/en/latest/installation.html), so I'd prefer to avoid mentioning it explicitly (to avoid tying us to transitive deps that can change and run the risk of becoming outdated), but I would support adding something along the lines of "and the CFFI dependencies" or "a working CFFI installation" (with a link to their docs) after "you will need to have a functioning C compiler" in our installation docs.

**Comment by thet** [comment]
Thank you!

I just installed RelStorage via buildout in a docker container. libcffi-dev wasn't available there, so I added this dependency it in the dockerfile. No big deal, except that debugging docker is more cumbersome than without a container.

RelStorage was installed as an egg, though:

```
$ grep -i relstorage bin/instance 
  '/plone/buildout/eggs/RelStorage-2.0.0-py2.7-linux-x86_64.egg',
```
