### ISSUE TITLE
MySQL and REPLACE INTO query

### ISSUE THREAD

**Issue by jplouis** [zodb/relstorage#189]
I searched but didn't see any discussion on pros and cons of using insert on duplicate key update vs the replace into queries used by relstorage.  Specifically changing the query as in the linked diff.

https://gist.github.com/daniel-garcia/2790549

**Comment by jamadden** [comment]
What are you trying to achieve? I'm not aware of any benchmark work in this area, but I'm also not aware of any performance issues in this area. This area of the code was recently looked at in #175 (and I'm not gun-shy about subqueries in MySQL based on that conversation).

**Comment by jplouis** [comment]
It was brought up as a possible issue with very large transactions on with MySQL running on a SAN. Seems like as the table gets bigger the query degrades.

**Comment by jamadden** [comment]
We'd need to go through a similar process as #175 of comparing query plans on all the supported database versions to if there's a definitive improvement.

/cc @jzuech3

**Comment by jamadden** [comment]
I've had another look at this, and I think it's worth seeing where we can use 'ON DUPLICATE KEY UPDATE', for a couple reasons

* It more closely matches Postgres's 'ON CONFLICT DO UPDATE SET'; we may be able to unify those queries and automatically make the small changes needed.
* It's documented as just performing an update if there's a conflict, whereas a 'REPLACE' is documented as deleting the existing row and inserting a new one; that's got to cause more work (IO, locks, etc) than just changing the existing values (for one thing, the primary key isn't changing, so there's no need to update primary key indexes with new row locations --- though the tables should be clustered on that key, so maybe the row locations don't change? But still, there's undo and redo info to record.)
* zodbshootout is in a better place to measure small differences in performance more repeatedly so I have more confidence in the results we can see there.
