### ISSUE TITLE
[Question] Does relstorage support MySQL Galera cluster?

### ISSUE THREAD

**Issue by JokerQyou** [zodb/relstorage#193]
According to Galera documentation [here][limitations], a Galera cluster does not support table locking including `GET_LOCK` and `RELEASE_LOCK`. I searched the codebase of relstorage, and did find the usage of `LOCK` functions. So is Galera cluster not supported?

[limitations]: http://galeracluster.com/documentation-webpages/limitations.html

**Comment by jamadden** [comment]
RelStorage [definitely uses `GET_LOCK`](https://github.com/zodb/relstorage/blob/master/relstorage/adapters/mysql/locker.py#L53) on MySQL, so if that's not supported then it's a no-go.
