### ISSUE TITLE
postgres: DatabaseError on crashed connection

### ISSUE THREAD

**Issue by agroszer** [zodb/relstorage#194]
We're trying to scale our PG with ELB and pgbouncer.
That config seems to drop connections after some timeout.

The below exception occurs occasionally, this seems to be also a sign of disconnect.

```
DatabaseError: server conn crashed?
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

  File "/opt/shoobx/shoobx.app/src/shoobx/app/tasks.py", line 186, in execute
    return task(*args, **kwargs)
  File "/opt/shoobx/shoobx.app/src/shoobx/app/tasks.py", line 735, in scheduledTaskRunner
    with taskcontext.rootContext() as root:
  File "python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/shoobx/shoobx.app/src/shoobx/app/taskcontext.py", line 77, in rootContext
    with celery_request() as req, interaction(req), transaction.manager as txn:
  File "python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/shoobx/shoobx.app/src/shoobx/app/taskcontext.py", line 41, in celery_request
    conn = db.open()
  File "ZODB/DB.py", line 791, in open
    result.open(transaction_manager)
  File "ZODB/Connection.py", line 923, in open
    self.newTransaction(None, False)
  File "ZODB/Connection.py", line 739, in newTransaction
    self._storage.sync(sync)
  File "relstorage/storage.py", line 1356, in sync
    self._rollback_load_connection()
  File "relstorage/storage.py", line 335, in _rollback_load_connection
    self._load_conn.rollback()
```

**Comment by jamadden** [comment]
The Python database API [specifies a set of exceptions](https://www.python.org/dev/peps/pep-0249/#exceptions) that drivers should implement. RelStorage knows about those, and understands [the ones](https://github.com/zodb/relstorage/blob/2.0.0/relstorage/storage.py#L1357) that are supposed to mean "database is disconnected" and will automatically reconnect if a `sync` gets one of those exceptions.


In the case of most DB-API compliant drivers, [those exceptions are](https://github.com/zodb/relstorage/blob/master/relstorage/adapters/_abstract_drivers.py#L47) OperationalError, InterfaceError, and our own ReplicaClosedException.

Unfortunately, [`DatabaseError` is the root of a hierarchy](http://initd.org/psycopg/docs/module.html#exceptions) and can mean almost anything, so it is not on the list of auto-reconnect exceptions.

I'm assuming you're using psycopg2. What version are you using? Before 2.6.2 or 2.7.2, there was [a bug](https://github.com/psycopg/psycopg2/commit/12317557da20d84baf12054d8dfce11ba8976cb6#diff-ba5ccc3a82e00243096b65624707763d) that sometimes caused DatabaseError to get raised when an OperationalError should have been, so the re-connect logic did not kick in. If you're on a prior version, upgrading should fix the problem. (Alternately you could try adding `DatabaseError` to the tuple of `disconnected_exceptions`. That may lead to some unexpected reconnections, and I don't really recommend it, but it may be a temporary fix for you.)

Before I found the bug fix, I spent some time tracing how errors are raised in psycopg2. These notes apply to older versions:

Tracing the execution path of `conn.rollback` in psycopg2 (`conn.rollback` -> `connection_type.c:psyco_conn_rollback` -> `connection_int.c:conn_rollback` -> `pqpath.c:pq_abort`) doesn't find that `DatabaseError` is explicitly being raised. Instead, `pq_abort` got an error state from the underlying libpq and [does its best to map it in `pq_complete_error`](https://github.com/psycopg/psycopg2/blob/master/psycopg/pqpath.c#L447) via `pg_raise` and [`exception_from_sqlstate`](https://github.com/psycopg/psycopg2/blob/master/psycopg/pqpath.c#L84).  Unfortunately it appears that, they miss this case, and instead return the generic DatabaseError, with the message [set by libpq](https://github.com/postgres/postgres/blob/master/src/interfaces/libpq/fe-misc.c#L805). (The bug fix is in pg_raise.)

Based on what I see in the psycopg2 driver code, it appears that they could probably distinguish this state too and return a better error (there are [documented error codes](https://www.postgresql.org/docs/current/static/errcodes-appendix.html) for this, but they may not be implemented; however, the connection state should always be set to `CONNECTION_BAD`---that's the bug fix) , thus solving the issue for all their clients.

**Comment by agroszer** [comment]
Thank you for the quick answer!

we're at `psycopg2==2.7.3.1` so meeeeh

(I'll continue later)

**Comment by jamadden** [comment]
From the bugfix, it appears that if there is an Postgres error code set, that will override the `CONNECTION_BAD` state. So there's still the chance that an unrecognised error code could result in a random DatabaseError. Debugging that would likely require building with PSYCOPG_DEBUG defined and setting the 'PSYCOPG_DEBUG' environment variable to see the various error debugging information.

**Comment by jamadden** [comment]
Closing since the conversation seems to have stalled for 18 months. Feel free to reopen if there's more to add.
