### ISSUE TITLE
Connecting to a database without hours of headaches and unnecessary BS

### ISSUE THREAD

**Issue by LoganDark** [zodb/relstorage#199]
Okay, apparently there's all this stuff with config files and weird formats and configuring things and other crap I don't want to deal with, I just want to connect to a database. I don't want to create a separate file just for relstorage, I just want to connect using an IP address, database name, username, and password. That's it. I don't want to go through the headache of configuring plone or zope or building recipes or zconfig files or other stuff like that.

**Comment by jimfulton** [comment]
On Mon, Apr 9, 2018 at 10:08 AM, LoganDark <notifications@github.com> wrote:

> Okay, apparently there's all this stuff with config files and weird
> formats and configuring things and other crap I don't want to deal with, I
> just want to connect to a database. I don't want to create a separate file
> just for relstorage, I just want to connect using an IP address, database
> name, username, and password. That's it. I don't want to go through the
> headache of configuring plone or zope or building recipes or config files
> or other stuff like that.
>
You don't need plone, zope, or buildout to use relstorage.

WRT configuration, at some point, you will want more control.

I agree, however, that it would be nice if RelStorage let you get started
without configuration.

If you just want to experiment with Postgres, you can try newt.db:

http://www.newtdb.org/en/latest/getting-started.html

which let's you just supply a connection string.  It's a thin wrapper
around RelStorage.

**Comment by LoganDark** [comment]
I need to use zodb with mySQL. Unless you can find a better way of using it on App Engine which doesn't support filesystem access...

**Comment by jimfulton** [comment]
On Mon, Apr 9, 2018 at 10:26 AM, LoganDark <notifications@github.com> wrote:

> I need to use zodb with mySQL. Unless you can find a better way of using
> it on App Engine which doesn't support filesystem access...
>

Postgres seems to be an option, albeit beta: https://cloud.google.com/sql/

If you need to use mySQL, you'll have to deal with creating a configuration
file.

**Comment by LoganDark** [comment]
> If you need to use mySQL, you'll have to deal with creating a configuration file

Then your library needs work.

**Comment by jamadden** [comment]
ZODB provides a trivial way to connect to a database using just a string: [`ZODB.config.databaseFromSting`](https://github.com/zopefoundation/ZODB/blob/master/src/ZODB/config.py#L44). Using it with relstorage is similarly trivial to get started:
```python
conf = """
%%import relstorage
<zodb main>
  <relstorage>
    <mysql>
      db %s
      user %s
      passwd %s
    </mysql>
  </relstorage>
</zodb>
""" % (dbname, user, passwd)

db = ZODB.config.databaseFromString(conf)
conn = db.open()
"""
```

In a real application you would want to supply additional configuration options for both ZODB and relstorage to adjust to the available load and resource usage.

If you consider that to be "unnecessary headache" and "BS" then pull requests are welcome.
