### ISSUE TITLE
`empty` is a keyword in MySQL 8; breaks history-preserving mode

### ISSUE THREAD

**Issue by viaYoung** [zodb/relstorage#201]
Relstorage is throwing error like below because 'empty' is reserved word after mysql 8.0.4.

    _mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the 
    manual that corresponds to your MySQL server version for the right syntax to use near 'empty       
    BOOLEAN NOT NULL DEFAULT FALSE,\nusername    BLOB NOT NULL,\ndescripti' at line 4")

**Comment by jamadden** [comment]
Thank you for the report. As of 8.0.4, [empty is now a keyword](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-E). Fixing it will require a schema change and migration. That's too big of a change for the legacy 1.x branch, but I will fix it for 2.x.

The offending schema is only used in history-preserving mode, so a workaround is to use history-free mode. 

Of course another workaround is to use MySQL < 8; RelStorage obviously hasn't been tested with MySQL 8 so I would tend to recommend sticking with MySQL 5.7 anyway.

**Comment by viaYoung** [comment]
Thank you. I reinstalled MySQL 5.7 now.
