### ISSUE TITLE
Possible to use sauna.reload with RelStorage?

### ISSUE THREAD

**Issue by neilferreira** [zodb/relstorage#203]
I am interested in using RelStorage with sauna.reload.  Upon installing RelStorage and Sauna at the same time, I get this exception:

```TypeError: ('Could not adapt', <relstorage.storage.RelStorage object at 0x10698a750>, <InterfaceClass sauna.reload.interfaces.IDatabaseHooks>)```

Has anyone ever attempted to go down this route, and determined if it would be possible?

**Comment by jamadden** [comment]
It won't be possible out of the box. `sauna.reload` wants hooks into the ZODB machinery and it only supports FileStorage and ZEO's ClientStorage natively. Indeed, it may not even work correctly with [recent ZEO releases](https://github.com/collective/sauna.reload/issues/19) as it is. 

One could probably develop the necessary adapters (they're probably pretty simple) and then either submit them to `sauna.reload` or package them as a separate package.

**Comment by jamadden** [comment]
There doesn't seem to be anything to do here. Closing.
