### ISSUE TITLE
Migrate to relstorage with ZRS

### ISSUE THREAD

**Issue by azmeuk** [zodb/relstorage#205]
Hi. I would like to migrate my database from filestorage(+zeo) to relstorage. My database takes several hours to convert with `zodbconvert` but I cannot afford to shut down my production service for hours.
I saw there is an incremental option to `zodbconverter` but it comes with warnings and freaky messages like `Use at your own risk.`, so I am not sure I want to use it.

After some tests I could manage to synchronize a ZEO + Filestorage datatabase to a ZEO + relstorage using ZRS. I know relstorage is not supposed to be used with ZEO, but it may allows me to migrate with a minor availability loss.

I did not find any documentation about this practice. Would you consider it risky or recommend it? If it seems safe, maybe the relstorage documentation should talk about it? What do you think?

Thank you for your answer.

**Comment by jimfulton** [comment]
It seems to me that this should work fine.  The ZEO server is just acting as a process container, as no one is actually accessing the database via ZEO.  You could as easily write a Python script that created a ZRS secondary storage around RelStorage and that just waited (e.g. by calling wait on an event) forever.

**Comment by gotcha** [comment]
@azmeuk For the record, did you use the technique you proposed herabove ? Did it work ?
