### ISSUE TITLE
lastTransaction() with Postgres adaptor does not update

### ISSUE THREAD

**Issue by lungj** [zodb/relstorage#341]
Calling the `lastTransaction()` method on the database object returns the same value after other threads update the object database and even after making local changes and committing. Perhaps related to transaction isolation level for the query?

Example code:

```
DEFAULT_REL_STORAGE = '''%import relstorage
<zodb main>
    <relstorage>
        <postgresql>
            dsn dbname='test' user='test' password='test' host='localhost'
        </postgresql>
    </relstorage>
</zodb>'''
import transaction
import ZODB
import ZODB.config
db = ZODB.config.databaseFromURL(DEFAULT_REL_STORAGE)
cn = db.open(transaction.manager)
print(cn.db().lastTransaction())
cn.root.test = 2
transaction.commit()
print(cn.db().lastTransaction()) # Expected that this is different from the last transaction ID.
```

**Comment by jamadden** [comment]
>  I was also trying syncing my connection for getting updates from other processes,

Generally that shouldn't be necessary. The transaction machinery, together with the ZODB connection, takes care of that on its own. In fact, if you `sync()` while a transaction is active, you can actually break things badly by creating an inconsistent view of the database: not all persistent objects are guaranteed to be from the same transaction.

If at all possible, I recommend using a transaction manager in explicit mode. That way, it's clear that your view of the database is consistent and up-to-date as of the time you call `manager.begin()` (plus it's more efficient).

**Comment by jamadden** [comment]
Oh, sorry, you meant syncing the *connection*, not the storage. Yes, that should be safe and consistent, but I also wouldn't usually recommend that outside of special purposes; instead begin and commit/abort transactions. Ideally also `close()` the connection between transactions so it can do some garbage collection; otherwise you may need to do that yourself.

Definitely don't sync a connection's storage manually though.

**Comment by lungj** [comment]
Sorry for the back-and-forth and thanks for your time :)

Based on your comments, I'm less sure that I'm doing the wrong thing (and more sure I'm doing the right thing). My code above was a simplification of a larger program that works fine with `relstorage`. Slightly different angle:

```
DEFAULT_REL_STORAGE = '''%import relstorage
<zodb main>
    <relstorage>
        <postgresql>
            dsn dbname='test' user='test' password='test' host='localhost'
        </postgresql>
    </relstorage>
</zodb>'''

import transaction
import ZODB
import ZODB.config
db = ZODB.config.databaseFromString(DEFAULT_REL_STORAGE)
cn = db.open(transaction.manager)
t1 = db.lastTransaction()

# In another process, update root and commit.

cn.sync()
t2 = db.lastTransaction()
assert t1 != t2 # Expected that this is different from the last transaction ID.
```

What I'm doing in the other process is I'm modifying `root` and then committing. I can _see_ the changes in the code above after the sync. However, `lastTransaction()` returns the old value. Am I forgetting to sync something?

**Comment by jamadden** [comment]
In your other transaction you probably need to `poll-invalidations`.  But again, for any storage type, this is absolutely not the recommended way to manage connections. Use transactions. And never use the methods on the DB object, those are horrible and non-transactional.
