### ISSUE TITLE
3.0 release?

### ISSUE THREAD

**Issue by krissik** [zodb/relstorage#349]
Thanks a lot for #348 !

Can you already give us a ball park figure on the release date of 3.0?

That would be great - but no worries if you don`t know yet!

**Comment by jamadden** [comment]
I don't know. There's [some milestones](https://github.com/zodb/relstorage/milestones) that track what I'd like to get done for a final release. Some of the less important ones may drop off though, based on how much time I can allocate to this.

I do hope to release 3.0a10 within a week or so.

Note that the 'a' means "not feature complete". It does not mean "unstable with serious known issues". We're running large production sites on 3.0a7 and 3.0a9 and  I would recommend those versions over 2.x; we no longer run 2.x in production at scale.

**Comment by krissik** [comment]
> Note that the 'a' means "not feature complete". It does not mean "unstable with serious known issues". We're running large production sites on 3.0a7 and 3.0a9 and I would recommend those versions over 2.x; we no longer run 2.x in production at scale.

Thanks - that is good to know.
