### ISSUE TITLE
unsupported operand type(s) for +: 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by flipmcf** [zodb/relstorage#391]
This issue is present in the 2.1.1 release - which is where we are pinned ATM.

The issue gets fixed here:
https://github.com/zodb/relstorage/commit/94977bf5c4062a1b0ce85c8cd7d834e473d92062#diff-f7b6ac153002a3eb85cdb3c87df8818eL39

 src/relstorage/adapters/mysql/stats.py

Is there a chance you can backport this fix to relstorage 2 and release a 2.1.2?

**Comment by jamadden** [comment]
I hadn't been planning on making any further releases of RS 2. Is one of the [minor incompatibilities](https://dev.nextthought.com/blog/2019/11/relstorage-30.html#id7) blocking an upgrade?

**Comment by flipmcf** [comment]
+1 for super fast reply!

I'm not sure what's blocking our upgrade.  I wasn't version pinned in our buildout and our build broke - that's all I knows.

 So I simply pinned to 2.1.1 and moved on with life to get the build back in order.

I know releasing a 2.1.2 would be a pain.  I'll think it over.

I can try 3.0 again, but we did get (unspecified) reports of our build failing.

**Comment by jamadden** [comment]
Thanks for investigating 3 again. We deploy 3 with buildout on macOS and Linux x86-64 without any issues. There was an earlier pre-release that didn't work with buildout at all, but that was an accident. And some of the earlier pre-releases didn't have binary wheels distributed so a working compiler for Python extensions was required, but the final releases do have binary wheels.

**Comment by flipmcf** [comment]
I'm not sure this is a valid bug now.

Is it possible that my 2.1.1 install was working,
  then 3.0.0 was installed - which created new views not present in 2.1.1
Then I rolled back to 2.1.1
Code broke because views existed.

Thoughts?

**Comment by jamadden** [comment]
Oh, that's a definite possibility!

**Comment by flipmcf** [comment]
This is the case.   Database was upgraded with 3.0.0 install then 2.1.1 code was placed on top.  Causing this issue.

Closing ticket.
