### ISSUE TITLE
relstorage pack issue with broken buckets

### ISSUE THREAD

**Issue by jakke** [zodb/relstorage#4]
When packing on a relstorage with a corrupted ZODB (broken index with BTree buckets), we got Unpickling errors. We got plone back working by reindexing the broken catalogs. But packing still was an issue.

On Filestorage the packing went fine, Relstorage still gave unpickling errors on the broken buckets. As far as I understood the code of Filestorage and Relstorage, the issue is caused by the following.
Filestorage loads the root object, finds the objects it refers to and does the same for these objects, putting that info in a list. All objects that are not in this list, can be removed by pack.
Relstorage seems to load all transactions in pre_pack, unpickling all objects in these transactions, and build a list of referenced objects with that information, so pack can decide which objects to remove.

The fundamental difference seems to be in the creation of the list. Filestorage does not access the old, broken index objects. Relstorage seems to access these broken objects anyway.
Our temporary workaround is by patching the ZODB/serialize.py, by putting the two u.noload() in referencesf() in a try/except block, where we just move on (pass) in case of an exception. This ignores the broken index bucket object, the correct list for pack seems to be build and the broken index bucket objects are removed from the ZODB.

Could you provide some feedback if my mental model is correct (or totally not), eventually a suggestion for a better workaround? 
I guess the cleanest solution would be if Relstorage could use the same approach as Filestorage to build up the list of what to keep and what to remove. But I also guess that’s not the best solution because of performance or other issues.

**Comment by hathawsh** [comment]
Closing due to no response from the submitter in 2 years.
