### ISSUE TITLE
How to add Demostorage before Postgres

### ISSUE THREAD

**Issue by NicolasGoeddel** [zodb/relstorage#410]
Hi,

I am unsure about using the Demostorage together with Relstorage. Is there any documentation about this or an example? Is it even possible? It gets only mentioned once on this page: https://relstorage.readthedocs.io/en/latest/zodburi.html?highlight=demostorage

> demostorage
>    boolean (if true, wrap RelStorage in a DemoStorage)

But if I go to the latest doc of zodburi it has a differect description: https://docs.pylonsproject.org/projects/zodburi/en/latest/

> demostorage
>     boolean (if true, wrap FileStorage in a DemoStorage) 

Is the documentation out of date? Or do I misunderstand something?

**Comment by jamadden** [comment]
Yes, it's certainly possible. The two documents are documenting different things, hence their different descriptions. You can use ZConfig, zodburi, or manually construct the objects.

**Comment by NicolasGoeddel** [comment]
Thank you. I'll have to try that next time. Right now I can't get around to it. If it works I will post my buildout here for everyone.
