### ISSUE TITLE
Documentation: Performance (outdated link, missing info about Relstorage 4)

### ISSUE THREAD

**Issue by pgrunewald** [zodb/relstorage#508]
In the performance section of the documentation: there is an outdated blog link to the performance improvements on Relstorage 3: https://dev.nextthought.com/blog/2019/11/relstorage-30.html

This website is not available anymore. Better change this to the archived version: https://web.archive.org/web/20211023115938/https://dev.nextthought.com/blog/2019/11/relstorage-30.html#performance-improvements

Additional, if available: A report about the improvements for Relstorage 4 could be presented here as well.

**Comment by jamadden** [comment]
The link was updated.

**Comment by mliebischer** [comment]
Perhaps a dumb question. But the changes with the new link from this commit https://github.com/zodb/relstorage/commit/f0ad99582e9925c045c33b6c76644c6b03029f0e somehow didn't make it into the master branch. 

It would be great if someone could merge the changes and update the ReadTheDocs page:
https://relstorage.readthedocs.io/en/latest/performance.html
