### ISSUE TITLE
Database wide locking does not scale

### ISSUE THREAD

**Issue by jensens** [zodb/relstorage#6]
Hi,

we are using here relstorage at a site with about 300k plone content items (dexterity based). So, it performs better than ZEO-Server. But we now got lots of conflict errors with relstorage (both, mysql and postgresql) on hi write scenarios, i.e. when an import is running and editors are working. We already have this distributed to different zope instances and machines. 

At least on mysql it seems the locking strategy is very paranoid. The whole database i locked explicit. Max, the database expert of our service provider, nailed it down to these locks, see https://github.com/zodb/relstorage/blob/master/relstorage/adapters/locker.py#L111 It means other db connections cant write to the DB while it is locked. Also at transaction commit time it waits at worst case the given timeout. 

But as far as i understand it is sufficient to take care only about modified objects, those joined to the transaction and identified by oid. Max proposed to keep a table of locked oid's instead of locking the whole thing. According to him using the usal mysql transactions its then possible get information about modified objects on oid level. 

I didnt digged deeper for now on this topic. But in my opinion current heavy locking behaviour is a real stopper for hi-write scenarios. It really blocks writing at some point.

Btw. Postgresql had an about 10-20% better write performance on hi write load. We cloned our complete environment (4 vms) and on thd db-vm we replaced mysql by postresql. But on hi-write it had the same problems. As I see from code it does table based locking and it seems since we have only a few tables this is finally the same as mysql database locks.

I'd like to read some opinions about this, also some background why this method of locking was choosen. I'am sure there is a good reason. May be simplicity? But if more complexity stops blocking on write I'd prefer it.

We would like to contribute making this work better if its possible.

regards Jens

**Comment by jamadden** [comment]
FWIW, RelStorage 3 no longer needs to hold the commit lock for anything other than allocating transaction  IDs. Conflict resolution, in particular, no longer needs the commit lock.
